version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - spring-net

  app:
    image: dockdockgo2001/spring-test:latest
    container_name: springboot-app
    depends_on:
      - postgres
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SERVER_PORT: 9191
    networks:
      - spring-net

volumes:
  pg_data:

networks:
  spring-net: